<#
.SYNOPSIS
    Bring up the ephemeral E2E MSSQL container and verify it is ready.

.DESCRIPTION
    Idempotent. On first run it generates db-migrations/tests/docker/.env.local
    (gitignored) with strong random secrets, then `docker compose up -d`, waits
    for the container healthcheck, and verifies:
      * SELECT 1 answers (SQL auth as sa),
      * the SQL Agent service is Running (the reset E2E needs it),
      * the server collation is Latin1_General_CI_AS (JTL-Wawi parity).

    Leaves the container running. Tear it down with teardown.ps1.

    Prod parity: SQL Server 2022 (see docker-compose.yml / README). Never targets
    a real server — it only talks to localhost,14330.

.PARAMETER Force
    Recreate .env.local even if it already exists (rotates the generated secrets).
    A running container keeps its original SA password until the next teardown -v,
    so use -Force only together with a fresh volume.

.EXAMPLE
    pwsh db-migrations/tests/docker/setup.ps1
#>
[CmdletBinding()]
param(
    [switch] $Force
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$envFile = Join-Path $scriptRoot '.env.local'
$composeFile = Join-Path $scriptRoot 'docker-compose.yml'

# --- prerequisites ----------------------------------------------------------
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw 'docker is not on PATH.'
}

# sqlcmd for the post-start verification (host side, SQL auth).
$sqlcmd = @('/usr/local/bin/sqlcmd', '/opt/mssql-tools18/bin/sqlcmd', 'sqlcmd') |
    ForEach-Object { Get-Command $_ -ErrorAction SilentlyContinue } |
    Select-Object -First 1
if (-not $sqlcmd) {
    throw 'No sqlcmd found (looked for /usr/local/bin/sqlcmd, /opt/mssql-tools18/bin/sqlcmd, sqlcmd on PATH).'
}

# --- secret generation ------------------------------------------------------
# Strong random, complexity-satisfying, single-quote-free (CertPassword constraint).
function New-Secret {
    # Safe symbol set excludes ' " ` $ \ to avoid shell/SQL-literal hazards.
    $upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ'.ToCharArray()
    $lower = 'abcdefghijkmnpqrstuvwxyz'.ToCharArray()
    $digit = '23456789'.ToCharArray()
    $sym   = '!#%&*+-_=.:'.ToCharArray()
    $all = $upper + $lower + $digit + $sym
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        function Pick($set) { $b = [byte[]]::new(1); $rng.GetBytes($b); $set[$b[0] % $set.Length] }
        # Guarantee one of each class, then fill to length 24.
        $chars = @((Pick $upper), (Pick $lower), (Pick $digit), (Pick $sym))
        while ($chars.Count -lt 24) { $chars += (Pick $all) }
        # Fisher-Yates shuffle so the class-seeded chars are not positionally fixed.
        for ($i = $chars.Count - 1; $i -gt 0; $i--) {
            $j = [int]([BitConverter]::ToUInt32((& { $b = [byte[]]::new(4); $rng.GetBytes($b); $b }), 0) % ($i + 1))
            $tmp = $chars[$i]; $chars[$i] = $chars[$j]; $chars[$j] = $tmp
        }
        -join $chars
    }
    finally { $rng.Dispose() }
}

if ($Force -and (Test-Path $envFile)) {
    Remove-Item $envFile -Force
    Write-Host 'Removed existing .env.local (-Force).' -ForegroundColor Yellow
}

if (-not (Test-Path $envFile)) {
    $sa = New-Secret
    $cert = New-Secret
    @(
        '# Generated by setup.ps1 — DO NOT COMMIT. See .env.example for the schema.'
        "MSSQL_SA_PASSWORD=$sa"
        "GRATE_CERT_PASSWORD=$cert"
    ) | Set-Content -Path $envFile -Encoding utf8
    # Best-effort tighten perms (no-op on filesystems without chmod).
    try { & chmod 600 $envFile 2>$null } catch { }
    Write-Host "Generated $envFile (strong random secrets)." -ForegroundColor Green
}
else {
    Write-Host "Reusing existing $envFile." -ForegroundColor Cyan
}

# Read the SA password back for the verification step.
$saPassword = (Get-Content $envFile |
    Where-Object { $_ -match '^\s*MSSQL_SA_PASSWORD\s*=' } |
    Select-Object -First 1) -replace '^\s*MSSQL_SA_PASSWORD\s*=\s*', ''
if ([string]::IsNullOrWhiteSpace($saPassword)) {
    throw "Could not read MSSQL_SA_PASSWORD from $envFile."
}

# --- bring up ---------------------------------------------------------------
Write-Host ''
Write-Host '==> docker compose up -d' -ForegroundColor Cyan
& docker compose --env-file $envFile -f $composeFile up -d
if ($LASTEXITCODE -ne 0) { throw "docker compose up failed (exit $LASTEXITCODE)." }

# --- wait for healthy -------------------------------------------------------
$container = 'robotico-e2e-mssql'
$deadline = (Get-Date).AddMinutes(4)
Write-Host ''
Write-Host "==> waiting for '$container' to become healthy ..." -ForegroundColor Cyan
do {
    Start-Sleep -Seconds 5
    $status = (& docker inspect --format '{{.State.Health.Status}}' $container 2>$null)
    Write-Host "    health: $status"
    if ($status -eq 'healthy') { break }
    if ((Get-Date) -gt $deadline) {
        & docker logs --tail 40 $container 2>&1 | Write-Host
        throw "Container did not become healthy within the timeout."
    }
} while ($true)

# --- verification -----------------------------------------------------------
$sqlcmdPath = $sqlcmd.Source
function Invoke-Check([string] $query) {
    # -C trust self-signed cert; -h -1 no headers; -W trim; -b nonzero exit on SQL error.
    $out = & $sqlcmdPath -S 'localhost,14330' -U sa -P $saPassword -C -h -1 -W -b -Q $query 2>&1
    if ($LASTEXITCODE -ne 0) { throw "sqlcmd failed for [$query]: $out" }
    return ($out | Where-Object { $_ -and $_.Trim() -ne '' }) -join "`n"
}

Write-Host ''
Write-Host '==> verification' -ForegroundColor Cyan

$select1 = Invoke-Check 'SET NOCOUNT ON; SELECT 1'
Write-Host "    SELECT 1        : $select1"

$agent = Invoke-Check "SET NOCOUNT ON; SELECT status_desc FROM sys.dm_server_services WHERE servicename LIKE '%Agent%'"
Write-Host "    SQL Agent       : $agent"
if ($agent -notmatch 'Running') {
    throw "SQL Agent is not Running (got '$agent'). The reset E2E requires MSSQL_AGENT_ENABLED=true."
}

$collation = Invoke-Check "SET NOCOUNT ON; SELECT CONVERT(sysname, SERVERPROPERTY('Collation'))"
Write-Host "    Collation       : $collation"
if ($collation -ne 'Latin1_General_CI_AS') {
    Write-Warning "Collation is '$collation', expected Latin1_General_CI_AS. Delete the volume (teardown.ps1) and re-run — MSSQL_COLLATION only applies on first volume init."
}

Write-Host ''
Write-Host "Ready. Container '$container' is healthy on localhost,14330 (SQL auth: sa)." -ForegroundColor Green
Write-Host "Next: deploy the chains — see db-migrations/tests/docker/README.md." -ForegroundColor Green
